---
  ecmaFeatures: {}
  extends:
    - airbnb-base
  plugins:
    - smells

  env:
    jasmine: true
    node: true

  globals:
    _: true

  rules:
    indent:
      - off
      - 2
      -
        SwitchCase: 1
        VariableDeclarator: 1
    comma-dangle:
      - error
      - never
    key-spacing: off
    quotes:
      - error
      - single
    func-names: off
    no-param-reassign: off
    curly:
      - error
      - all
    no-use-before-define:
      - error
      - nofunc
    spaced-comment: off
    quote-props:
      - error
      - as-needed
      -
        keywords: true
    no-multi-spaces:
      - off
      -
        exceptions:
          VariableDeclarator: true
    no-shadow: off
    max-len:
      - error
      - 120
      - 4
      -
        ignoreComments: true
        ignoreUrls: true

    arrow-body-style:
      - error
      - as-needed
    arrow-parens:
      - off
      - as-needed

    no-console: warn

    object-curly-spacing:
      - error
      - always
    array-bracket-spacing:
      - error
      - never
    computed-property-spacing:
      - error
      - never
    template-curly-spacing:
      - error
      - always
    space-in-parens:
      - error
      - never

    complexity:
      - error
      - 7
    no-extra-boolean-cast: error
    no-void: error
    max-depth:
      - error
      - 3
    max-statements:
      - error
      - 15
    max-params:
      - error
      - 5
    max-nested-callbacks:
      - error
      - 3

    no-bitwise:
      - error

    newline-after-var: error
    newline-before-return: error
    newline-per-chained-call: error

    no-continue: error
    no-undefined: error
    no-this-before-super: error
    prefer-spread: error

    no-mixed-operators: off

    smells/no-this-assign: error

    import/no-unresolved: off
    import/no-duplicates: error
    import/no-extraneous-dependencies: off
