---
  ecmaFeatures: {}
  extends:
    - airbnb-base
    - angular
  plugins:
    - smells

  env:
    jasmine: true

  globals:
    inject: true
    appConfig: true

  rules:
    indent:
      - error
      - 2
      -
        SwitchCase: 1
        VariableDeclarator: 1
    comma-dangle:
      - error
      - never
    key-spacing: off
    quotes:
      - error
      - single
    func-names: off
    no-param-reassign: off
    curly:
      - error
      - all
    no-use-before-define:
      - error
      - nofunc
    spaced-comment: off
    quote-props:
      - error
      - as-needed
      -
        keywords: true
    no-multi-spaces:
      - off
      -
        exceptions:
          VariableDeclarator: true
    no-shadow: off
    max-len:
      - error
      - 120
      - 4
      -
        ignoreComments: true
        ignoreUrls: true

    prefer-arrow-callback: error
    arrow-body-style:
      - error
      - as-needed
    arrow-parens:
      - error
      - as-needed

    no-console: warn

    object-curly-spacing:
      - error
      - always
    array-bracket-spacing:
      - error
      - never
    computed-property-spacing:
      - error
      - never
    template-curly-spacing:
      - error
      - always
    space-in-parens:
      - error
      - never

    complexity:
      - error
      - 7
    no-extra-boolean-cast: error
    no-void: error
    max-depth:
      - error
      - 3
    max-statements:
      - error
      - 15
    max-params:
      - error
      - 5
    max-nested-callbacks:
      - error
      - 3

    no-bitwise:
      - error

    newline-after-var: error
    newline-before-return: error
    newline-per-chained-call: error

    no-continue: error
    no-undefined: error
    no-this-before-super: error
    prefer-spread: error

    no-mixed-operators: off

    smells/no-this-assign: error

    angular/angularelement: error
    angular/controller-as-vm:
      - off
      - self
    angular/controller-name:
      - error
      - /[A-Z].*Ctrl$/
    angular/di:
      - off
      - function
    angular/di-order:
      - error
      - true
    angular/di-unused: error
    angular/directive-name:
      - error
      - mih
    angular/directive-restrict:
      - off
      -
        restrict: AE
        explicit: never
    angular/component-limit:
      - off
      - 2
    angular/empty-controller: error
    angular/file-name:
      - off
      -
        nameStyle: dash
        typeSeparator: dot
        ignorePrefix: mih
        ignoreTypeSuffix: true
    angular/filter-name: off
    angular/function-type:
      - error
      - named
    angular/module-dependency-order:
      - off
      -
        grouped: true
        prefix: mih
    angular/module-name:
      - error
      - mih
    angular/no-inline-template:
      - error
      -
        allowSimple: true
    angular/no-private-call:
      - error
      -
        allow:
          - $$postDigest
    angular/no-services:
      - error
      -
        controller:
          - $resource
        diretive:
          - $resource
    angular/service-name:
      - error
      - /.*(Fct|Srv|Const|Val)$/
    angular/rest-service:
      - error
      - $resource
    angular/log: warn
    angular/watchers-execution:
      - 2
      - $apply

    import/no-unresolved: off
    import/no-duplicates: error
    import/no-extraneous-dependencies: off
